package view;

import java.awt.Color;

/**
 *
 * @author alexandermunoznava
 */
public class FormSudoku extends javax.swing.JFrame {
    
    public static SudokuBoard sudokuBoard;
    private NumbersBoard numbersBoard;
    private FormLevels formLevels;
    private boolean createState;
    
    private int xPos;
    private int yPos;
    
    public FormSudoku() {
        initComponents();
        
        iniciarComponentes();
    }
    
    public void iniciarComponentes(){
        sudokuBoard = new SudokuBoard();
        sudokuBoard.setTxtHeight(36);
        sudokuBoard.setTxtWidth(36);
        sudokuBoard.setTxtMargin(4);
        sudokuBoard.setTxtFontsize(27);
        
        sudokuBoard.setPanelBackground(new Color(89,43,25));
        
        sudokuBoard.setTxtBackground1(Color.white);
        sudokuBoard.setTxtForeground1(new Color(153,1,1));
        sudokuBoard.setTxtBackground2(new Color(232, 186, 186));
        sudokuBoard.setTxtForeground2(Color.black);
        sudokuBoard.setTxtBackground3(new Color(203,102,102));
        sudokuBoard.setTxtForeground3(Color.white);
        sudokuBoard.setTxtBackground4(new Color(235, 227, 227));
        sudokuBoard.setTxtForeground4(Color.black);
        panelFondo.add(sudokuBoard);
        sudokuBoard.setLocation(70, 60);
        sudokuBoard.setVisible(true);
        sudokuBoard.createSudoku();
        
        numbersBoard = new NumbersBoard();
        numbersBoard.setTxtWidth(36);
        numbersBoard.setTxtHeight(36);
        numbersBoard.setTxtMargin(4);
        numbersBoard.setTxtFontsize(37);
        numbersBoard.setPanelBackground(new Color(89, 43, 25));
        numbersBoard.setTxtBackground1(new Color(239, 229, 216));
        numbersBoard.setTxtForeground1(new Color(89, 43, 25));
        numbersBoard.setTxtBackground2(new Color(143, 72, 72));
        numbersBoard.setTxtForeground2(Color.WHITE);
        panelFondo.add(numbersBoard);
        numbersBoard.createBoard();
        numbersBoard.setLocation(20, 60);
        numbersBoard.setVisible(true);
        
        sudokuBoard.generateSudoku(2);
        createState = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSolution = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNewGame = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblClean = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCreate = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblCheck = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        New Game");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("        New Game");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("        New Game");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(80, 43, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(51, 153, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(540, 420));
        panelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelFondoMouseDragged(evt);
            }
        });
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });
        panelFondo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Krub", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sudoku");
        panelFondo.add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 30);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        lblSolution.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        lblSolution.setForeground(new java.awt.Color(255, 255, 255));
        lblSolution.setText("            Solution");
        lblSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSolution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSolutionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(jPanel1);
        jPanel1.setBounds(420, 330, 150, 40);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        lblNewGame.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        lblNewGame.setForeground(new java.awt.Color(255, 255, 255));
        lblNewGame.setText("        New Game");
        lblNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewGameMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(jPanel3);
        jPanel3.setBounds(420, 60, 150, 40);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        lblClean.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        lblClean.setForeground(new java.awt.Color(255, 255, 255));
        lblClean.setText("              Clean");
        lblClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCleanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClean, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClean, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(jPanel4);
        jPanel4.setBounds(420, 120, 150, 40);

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        lblCreate.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblCreate.setText("             Create");
        lblCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCreateMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(jPanel5);
        jPanel5.setBounds(420, 190, 150, 40);

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        lblCheck.setFont(new java.awt.Font("Lantinghei SC", 0, 14)); // NOI18N
        lblCheck.setForeground(new java.awt.Color(255, 255, 255));
        lblCheck.setText("             Check");
        lblCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCheckMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(jPanel6);
        jPanel6.setBounds(420, 260, 150, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelFondo.add(jLabel2);
        jLabel2.setBounds(640, 0, 50, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void lblNewGameMousePressed(java.awt.event.MouseEvent evt) {                                        
        if (formLevels != null) {
            formLevels.setVisible(true);
        } else {
            formLevels = new FormLevels(sudokuBoard);
            formLevels.setVisible(true);
        }
    }                                       

    private void lblCleanMousePressed(java.awt.event.MouseEvent evt) {                                      
        sudokuBoard.clean();
    }                                     

    private void lblCreateMousePressed(java.awt.event.MouseEvent evt) {                                       
        if (createState) {
            lblNewGame.setVisible(false);
            lblClean.setVisible(false);
            lblCheck.setVisible(false);
            lblSolution.setVisible(false);
            createState = false;
            sudokuBoard.txtClean();
        } else {
            if (sudokuBoard.createCustomSudoku()) {
                lblNewGame.setVisible(true);
                lblClean.setVisible(true);
                lblCheck.setVisible(true);
                lblSolution.setVisible(true);
                createState = true;
                lblCreate.setText("           CREATE");
            }
        }
    }                                      

    private void lblCheckMousePressed(java.awt.event.MouseEvent evt) {                                      
        sudokuBoard.check();
    }                                     

    private void lblSolutionMousePressed(java.awt.event.MouseEvent evt) {                                         
        sudokuBoard.resolve();
    }                                        

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }                                    

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {                                        
        xPos = evt.getX();
        yPos = evt.getY();
    }                                       

    private void panelFondoMouseDragged(java.awt.event.MouseEvent evt) {                                        
        this.setLocation(evt.getXOnScreen() - xPos, evt.getYOnScreen() - yPos);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSudoku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblClean;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblNewGame;
    private javax.swing.JLabel lblSolution;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration                   
}
