package view;

import java.awt.Color;

/**
 *
 * @author alexandermunoznava
 */
public class FormSudoku extends javax.swing.JFrame {
    
    private SudokuBoard sudokuBoard;
    private NumbersBoard numbersBoard;
    
    public FormSudoku() {
        initComponents();
        
        iniciarComponentes();
    }
    
    public void iniciarComponentes(){
        sudokuBoard = new SudokuBoard();
        sudokuBoard.setTxtHeight(36);
        sudokuBoard.setTxtWidth(36);
        sudokuBoard.setTxtMargin(4);
        sudokuBoard.setTxtFontsize(27);
        
        sudokuBoard.setPanelBackground(new Color(89,43,25));
        
        sudokuBoard.setTxtBackground1(Color.white);
        sudokuBoard.setTxtForeground1(Color.black);
        sudokuBoard.setTxtBackground2(new Color(232, 186, 186));
        sudokuBoard.setTxtForeground2(Color.black);
        sudokuBoard.setTxtBackground3(new Color(203,102,102));
        sudokuBoard.setTxtForeground3(Color.white);
        panelFondo.add(sudokuBoard);
        sudokuBoard.setLocation(70, 60);
        sudokuBoard.setVisible(true);
        sudokuBoard.createSudoku();
        
        numbersBoard = new NumbersBoard();
        numbersBoard.setTxtWidth(36);
        numbersBoard.setTxtHeight(36);
        numbersBoard.setTxtMargin(4);
        numbersBoard.setTxtFontsize(37);
        numbersBoard.setPanelBackground(new Color(89, 43, 25));
        numbersBoard.setTxtBackground1(new Color(239, 229, 216));
        numbersBoard.setTxtForeground1(new Color(89, 43, 25));
        numbersBoard.setTxtBackground2(new Color(143, 72, 72));
        numbersBoard.setTxtForeground2(Color.WHITE);
        panelFondo.add(numbersBoard);
        numbersBoard.createBoard();
        numbersBoard.setLocation(20, 60);
        numbersBoard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 153, 153));
        panelFondo.setPreferredSize(new java.awt.Dimension(540, 420));
        panelFondo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Krub", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sudoku");
        panelFondo.add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSudoku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration                   
}
